name: CI

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go: ['stable']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test ./... -coverprofile=coverage.txt

      - name: Create Tag
        if: success()  # 仅在测试成功时运行
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          VERSION="$(go run ./cmd -v | tail -n 1 | tr -d '\r')"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid component version: $VERSION" >&2
            exit 1
          fi
          TAG="${VERSION}-$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        if: success()
        run: |
          sed -i "s|go get github.com/oneclickvirt/cputest@.*|go get github.com/oneclickvirt/cputest@${{ env.TAG }}|" README.md
          git add README.md
          git commit -m "Update README with latest tag ${{ env.TAG }}"
          git push origin main  # 修改为你的默认分支名称
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
